export const UPDATE_DASHBOARD_MODAL = "UPDATE_DASHBOARD_MODAL";
export const SET_USER_ADDRESS = "SET_USER_ADDRESS";
export const SET_USER_BALANCE = "SET_USER_BALANCE";
export const SET_USER_HEX = "SET_USER_HEX";
export const SET_UPCOMING_MATCH_FIXTURE_ID = "SET_UPCOMING_MATCH_FIXTURE_ID";
export const SET_USER_DETAILS = "SET_USER_DETAILS";